env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh -
script:
    - rustc --version
    - RUST_BACKTRACE=1 make -k
notifications:
    email:
        - damien.schoof+github@gmail.com
